import { Form, Input, InputNumber, Select, Switch } from 'antd';

export const ShadowsocksForm = () => <><Form.Item name={['protocolConfig','cipher']} label="Cipher"><Select options={[{value:'aes-256-gcm'},{value:'chacha20-ietf-poly1305'},{value:'2022-blake3-aes-256-gcm'}]} /></Form.Item><Form.Item name={['protocolConfig','password']} label="Password"><Input.Password /></Form.Item><Form.Item name={['protocolConfig','plugin']} label="Plugin"><Input /></Form.Item><Form.Item name={['protocolConfig','plugin-opts']} label="Plugin Options"><Input.TextArea rows={2} /></Form.Item></>;
export const VmessForm = () => <><Form.Item name={['protocolConfig','uuid']} label="UUID"><Input /></Form.Item><Form.Item name={['protocolConfig','alterId']} label="Alter ID"><InputNumber min={0} style={{width:'100%'}} /></Form.Item><Form.Item name={['protocolConfig','cipher']} label="Cipher"><Select options={[{value:'auto'},{value:'zero'},{value:'aes-128-gcm'},{value:'chacha20-poly1305'}]} /></Form.Item><Form.Item name={['protocolConfig','network']} label="Network"><Select options={[{value:'tcp'},{value:'ws'},{value:'grpc'},{value:'h2'}]} /></Form.Item><Form.Item name={['protocolConfig','tls']} label="TLS" valuePropName="checked"><Switch /></Form.Item><Form.Item name={['protocolConfig','servername']} label="Server Name"><Input /></Form.Item></>;
export const VlessForm = () => <><Form.Item name={['protocolConfig','uuid']} label="UUID"><Input /></Form.Item><Form.Item name={['protocolConfig','flow']} label="Flow"><Input placeholder="xtls-rprx-vision" /></Form.Item><Form.Item name={['protocolConfig','encryption']} label="Encryption"><Input placeholder="none" /></Form.Item><Form.Item name={['protocolConfig','reality']} label="Reality" valuePropName="checked"><Switch /></Form.Item><Form.Item name={['protocolConfig','tls']} label="TLS" valuePropName="checked"><Switch /></Form.Item><Form.Item name={['protocolConfig','network']} label="Network"><Select options={[{value:'tcp'},{value:'ws'},{value:'grpc'}]} /></Form.Item></>;
export const TrojanForm = () => <><Form.Item name={['protocolConfig','password']} label="Password"><Input.Password /></Form.Item><Form.Item name={['protocolConfig','sni']} label="SNI"><Input /></Form.Item><Form.Item name={['protocolConfig','tls']} label="TLS" valuePropName="checked"><Switch /></Form.Item></>;
export const Hysteria2Form = () => <><Form.Item name={['protocolConfig','password']} label="Password"><Input.Password /></Form.Item><Form.Item name={['protocolConfig','obfs']} label="OBFS"><Input /></Form.Item><Form.Item name={['protocolConfig','up']} label="Upload Speed"><Input placeholder="100 Mbps" /></Form.Item><Form.Item name={['protocolConfig','down']} label="Download Speed"><Input placeholder="100 Mbps" /></Form.Item></>;
export const WireGuardForm = () => <><Form.Item name={['protocolConfig','private-key']} label="Private Key"><Input.Password /></Form.Item><Form.Item name={['protocolConfig','public-key']} label="Public Key"><Input /></Form.Item><Form.Item name={['protocolConfig','ip']} label="IP"><Input /></Form.Item><Form.Item name={['protocolConfig','mtu']} label="MTU"><InputNumber min={576} max={9000} style={{width:'100%'}} /></Form.Item></>;
export const TuicForm = () => <><Form.Item name={['protocolConfig','uuid']} label="UUID"><Input /></Form.Item><Form.Item name={['protocolConfig','password']} label="Password"><Input.Password /></Form.Item></>;
