import React, { useState } from 'react';
import { Typography, Row, Col, Card, Button, Space, Form, Input, Select, Switch, Tabs, message } from 'antd';
import { SaveOutlined, DownloadOutlined, ReloadOutlined, SettingOutlined } from '@ant-design/icons';
import { apiRequest, apiUrl } from '../api/request';

const { Title, Paragraph } = Typography;
const { TextArea } = Input;

const Config: React.FC = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    await form.validateFields();
    setLoading(true);
    try {
      await apiRequest('/config/generate', { method: 'POST' });
      message.success('Configuration generated successfully.');
    } catch (err) {
      message.error((err as { message?: string }).message || 'Failed to generate configuration.');
    } finally { setLoading(false); }
  };

  const handleHotReload = async () => {
    setLoading(true);
    try {
      await apiRequest('/mihomo/restart', { method: 'POST' });
      message.success('Mihomo service reloaded configuration!');
    } catch (err) { message.error((err as { message?: string }).message || 'Network connection error.'); }
    finally { setLoading(false); }
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <div>
          <Title level={2} style={{ margin: 0 }}>Mihomo Config Engine</Title>
          <Paragraph style={{ margin: 0 }}>Manage Mihomo configuration visually. The final YAML is generated by the backend template engine.</Paragraph>
        </div>
      </div>
      <Row gutter={[24, 24]}>
        <Col xs={24} lg={16}>
          <Card title={<Space><SettingOutlined /><span>Visual Configuration Modules</span></Space>} bordered={false}>
            <Form form={form} layout="vertical" initialValues={{ mode: 'rule', logLevel: 'info', allowLan: false, dnsEnable: true, fakeIp: true }}>
              <Tabs items={[
                { key: 'general', label: 'General', children: <Row gutter={16}><Col span={8}><Form.Item name="mode" label="Mode"><Select options={[{value:'rule'},{value:'global'},{value:'direct'}]} /></Form.Item></Col><Col span={8}><Form.Item name="logLevel" label="Log Level"><Select options={[{value:'info'},{value:'warning'},{value:'error'},{value:'debug'}]} /></Form.Item></Col><Col span={8}><Form.Item name="allowLan" label="Allow LAN" valuePropName="checked"><Switch /></Form.Item></Col></Row> },
                { key: 'dns', label: 'DNS', children: <Row gutter={16}><Col span={8}><Form.Item name="dnsEnable" label="Enable" valuePropName="checked"><Switch /></Form.Item></Col><Col span={8}><Form.Item name="fakeIp" label="Fake IP" valuePropName="checked"><Switch /></Form.Item></Col><Col span={24}><Form.Item name="nameserver" label="Nameserver"><Select mode="tags" placeholder="223.5.5.5, 1.1.1.1" /></Form.Item></Col></Row> },
                { key: 'proxy', label: 'Proxy', children: <Form.List name="proxies">{(fields, { add, remove }) => <Space direction="vertical" style={{ width: '100%' }}>{fields.map((field) => <Card key={field.key} size="small"><Row gutter={12}><Col span={8}><Form.Item {...field} name={[field.name, 'name']} label="Node Name"><Input /></Form.Item></Col><Col span={8}><Form.Item {...field} name={[field.name, 'type']} label="Type"><Input /></Form.Item></Col><Col span={8}><Form.Item {...field} name={[field.name, 'server']} label="Server"><Input /></Form.Item></Col></Row><Button danger onClick={() => remove(field.name)}>Remove</Button></Card>)}<Button onClick={() => add()}>Add Proxy</Button></Space>}</Form.List> },
                { key: 'group', label: 'Proxy Group', children: <Form.Item name="proxyGroups" label="Strategy Groups"><TextArea rows={6} placeholder="One strategy group per line" /></Form.Item> },
                { key: 'rule', label: 'Rule', children: <Form.Item name="rules" label="Rules"><TextArea rows={8} placeholder="DOMAIN-SUFFIX,example.com,DIRECT" /></Form.Item> },
                { key: 'listener', label: 'Listener', children: <Form.Item name="listeners" label="Listeners"><TextArea rows={6} placeholder="Managed in Nodes page; add notes here if needed." /></Form.Item> },
              ]} />
            </Form>
          </Card>
        </Col>
        <Col xs={24} lg={8}>
          <Card title="Config Control Center" bordered={false}>
            <Space direction="vertical" style={{ width: '100%' }} size="middle">
              <Button type="primary" icon={<SaveOutlined />} block loading={loading} onClick={handleGenerate}>Save & Generate config.yaml</Button>
              <Button icon={<DownloadOutlined />} block onClick={() => window.open(apiUrl('/config/download'), '_blank')}>Download config.yaml</Button>
              <Button icon={<ReloadOutlined />} danger block loading={loading} onClick={handleHotReload}>Trigger Hot Reload</Button>
            </Space>
          </Card>
        </Col>
      </Row>
    </div>
  );
};

export default Config;
